site_name: Paparazzi
site_url: https://cashapp.github.io/paparazzi/
repo_name: Paparazzi
repo_url: https://github.com/cashapp/paparazzi
site_description: "Android screenshots without Android"
site_author: Square, Inc.
remote_branch: gh-pages

copyright: 'Copyright &copy; 2019 Square, Inc.'

theme:
  name: 'material'
  favicon: images/icon-square.png
  logo: images/icon-square.png
  palette:
    primary: 'light blue'
    accent: 'blue'

extra_css:
  - 'css/app.css'

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - tables

nav:
  - 'Overview': index.md
  - '1.x API': 1.x/paparazzi/app.cash.paparazzi/index.md
  - 'Change Log': changelog.md
  - 'Code of Conduct': code_of_conduct.md
  - 'Stack Overflow ‚èè': https://stackoverflow.com/questions/tagged/paparazzi?sort=active

