[versions]
agp = "8.1.1"
androidTools = "31.1.2" # == 23.0.0 + agp version
bytebuddy = "1.14.9"
composeCompiler = "1.5.1"
javaTarget = "11"
kotlin = "1.9.0"
ksp = "1.9.0-1.0.13"
ktlint = "0.50.0"
moshi = "1.15.0"

minSdk = "25"
compileSdk = "33"

# Maps to this commit: https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/5e972ea
layoutlib = "2022.3.1-5e972ea"
layoutlibPrebuiltSha = "5e972ea"

[libraries]
androidx-annotations = { module = "androidx.annotation:annotation", version = "1.7.0" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1" }
androidx-lifecycleCommon = { module = "androidx.lifecycle:lifecycle-common", version = "2.6.2" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version = "1.3.2" }

bytebuddy-agent = { module = "net.bytebuddy:byte-buddy-agent", version.ref = "bytebuddy" }
bytebuddy-core = { module = "net.bytebuddy:byte-buddy", version.ref = "bytebuddy" }

compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
composeUi-material = { module = "androidx.compose.material:material", version = "1.5.4" }
composeUi-uiTooling = { module = "androidx.compose.ui:ui-tooling" }

grgit = { module = "org.ajoberstar.grgit:grgit-core", version = "5.2.0" }
guava = { module = "com.google.guava:guava", version = "32.0.1-jre" }

kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version = "1.7.3" }

ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }

ktlint = { module = "com.pinterest.ktlint:ktlint-rule-engine", version.ref = "ktlint" }

kxml2 = { module = "kxml2:kxml2", version = "2.3.0" }

layoutlib-native-jdk11 = { module = "app.cash.paparazzi:layoutlib-native-jdk11", version.ref = "layoutlib" }
layoutlib-native-linux = { module = "app.cash.paparazzi:layoutlib-native-linux", version.ref = "layoutlib" }
layoutlib-native-macArm = { module = "app.cash.paparazzi:layoutlib-native-macarm", version.ref = "layoutlib" }
layoutlib-native-macOsX = { module = "app.cash.paparazzi:layoutlib-native-macosx", version.ref = "layoutlib" }
layoutlib-native-windows = { module = "app.cash.paparazzi:layoutlib-native-win", version.ref = "layoutlib" }

moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi" }
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlinCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }

okio = { module = "com.squareup.okio:okio", version = "3.6.0" }

tools-common = { module = "com.android.tools:common", version.ref = "androidTools" }
tools-layoutlib = { module = "com.android.tools.layoutlib:layoutlib-api", version = "31.1.1" }
tools-ninepatch = { module = "com.android.tools:ninepatch", version.ref = "androidTools" }
tools-sdkCommon = { module = "com.android.tools:sdk-common", version.ref = "androidTools" }

trove4j = { module = "org.jetbrains.intellij.deps:trove4j", version = "1.0.20200330" }

# Test libraries
junit = { module = "junit:junit", version = "4.13.2" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version = "1.13" }
truth = { module = "com.google.truth:truth", version = "1.1.5" }

# Plugins
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "agp" }
plugin-buildConfig = { module = "com.github.gmazzo.buildconfig:plugin", version = "4.1.2" }
plugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.9.10" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
plugin-mavenPublish = { module = "com.vanniktech:gradle-maven-publish-plugin", version = "0.25.3" }
plugin-spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.22.0" }
plugin-versions = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.48.0" }
